# Generated by Django 3.0.11 on 2023-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCookie', models.CharField(max_length=7)),
                ('no_hp', models.CharField(max_length=14)),
                ('jumlah_cup', models.SmallIntegerField()),
                ('omset_kotor', models.CharField(max_length=21)),
                ('hpp', models.CharField(max_length=21)),
                ('karyawan', models.IntegerField()),
                ('laba_kotor', models.CharField(max_length=21)),
                ('listrik', models.CharField(max_length=14)),
                ('lain', models.CharField(max_length=14)),
                ('operasional', models.CharField(max_length=14)),
                ('sewa_bangunan', models.CharField(max_length=14)),
                ('laba_bersih', models.CharField(max_length=14)),
                ('bep', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('total_today', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCookie', models.CharField(max_length=7)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
