# Generated by Django 3.0.11 on 2023-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcollection',
            name='bep',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='hpp',
            field=models.CharField(default='0', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='idCookie',
            field=models.CharField(default='0', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='jumlah_cup',
            field=models.CharField(default='0', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='karyawan',
            field=models.CharField(default='0', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='laba_bersih',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='laba_kotor',
            field=models.CharField(default='0', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='lain',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='listrik',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='no_hp',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='omset_kotor',
            field=models.CharField(default='0', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='operasional',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='sewa_bangunan',
            field=models.CharField(default='0', max_length=14, null=True),
        ),
    ]
