# Generated by Django 3.0.11 on 2023-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230927_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='laba_bersih',
            field=models.CharField(default='0', max_length=17, null=True),
        ),
    ]
