# Generated by Django 4.2.6 on 2023-12-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20231003_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=40, null=True)),
                ('reference_link', models.CharField(default='', max_length=40, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
