# Generated by Django 4.2.6 on 2023-12-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference_link',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
