# Generated by Django 3.0.11 on 2024-01-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_article_img'),
        ('apps', '0010_auto_20231228_1632'),
    ]

    operations = [
    ]
